use materiales_ibarra;

db.materiales.updateOne({nombre: "Cemento Gris (42.5 kg)"}, {$set: {costo: 8.75}});
db.materiales.updateOne({nombre: "Bloque de Concreto (hueco)"}, {$set: {costo: 0.90}});
db.materiales.updateOne({nombre: "Arena Fina (m³)"}, {$set: {costo: 19.00}});
db.materiales.updateOne({nombre: "Piedra Triturada (m³)"}, {$set: {costo: 23.50}});
db.materiales.updateOne({nombre: "Varilla Corrugada 3/8\""}, {$set: {costo: 13.75}});
db.materiales.updateOne({nombre: "Varilla Corrugada 1/2\""}, {$set: {costo: 18.50}});
db.materiales.updateOne({nombre: "Alambre de Amarre #18"}, {$set: {costo: 6.00}});
db.materiales.updateOne({nombre: "Clavo de 2\" (kg)"}, {$set: {costo: 2.90}});
db.materiales.updateOne({nombre: "Clavo de 3\" (kg)"}, {$set: {costo: 2.90}});
db.materiales.updateOne({nombre: "Madera Pino (pulgada)"}, {$set: {costo: 4.90}});
db.materiales.updateOne({nombre: "Tubo PVC 1/2\" (3m)"}, {$set: {costo: 3.75}});
db.materiales.updateOne({nombre: "Tubo PVC 3/4\" (3m)"}, {$set: {costo: 4.50}});
db.materiales.updateOne({nombre: "Codo PVC 1/2\""}, {$set: {costo: 0.95}});
db.materiales.updateOne({nombre: "Tee PVC 1/2\""}, {$set: {costo: 1.20}});
db.materiales.updateOne({nombre: "Pegamento PVC (946ml)"}, {$set: {costo: 7.00}});
db.materiales.updateOne({nombre: "Cinta Teflón (rollo)"}, {$set: {costo: 1.10}});
db.materiales.updateOne({nombre: "Lija para Madera #100"}, {$set: {costo: 0.60}});
db.materiales.updateOne({nombre: "Brocha 2\""}, {$set: {costo: 2.25}});
db.materiales.updateOne({nombre: "Rodillo para Pintura 9\""}, {$set: {costo: 4.00}});
db.materiales.updateOne({nombre: "Bandeja para Pintura"}, {$set: {costo: 2.50}});
db.materiales.updateOne({nombre: "Pintura Latex Blanca (gal)"}, {$set: {costo: 26.00}});
db.materiales.updateOne({nombre: "Pintura Esmalte Azul (gal)"}, {$set: {costo: 32.50}});
db.materiales.updateOne({nombre: "Pintura Esmalte Rojo (gal)"}, {$set: {costo: 32.50}});
db.materiales.updateOne({nombre: "Thinner (gal)"}, {$set: {costo: 14.00}});
db.materiales.updateOne({nombre: "Sellador (gal)"}, {$set: {costo: 17.00}});
db.materiales.updateOne({nombre: "Masilla (kg)"}, {$set: {costo: 5.00}});
db.materiales.updateOne({nombre: "Espátula 4\""}, {$set: {costo: 3.00}});
db.materiales.updateOne({nombre: "Cinta de Enmascarar (24mm)"}, {$set: {costo: 1.35}});
db.materiales.updateOne({nombre: "Cable THHN #12 (100m)"}, {$set: {costo: 40.00}});
db.materiales.updateOne({nombre: "Cable THHN #10 (100m)"}, {$set: {costo: 61.50}});
db.materiales.updateOne({nombre: "Interruptor Sencillo"}, {$set: {costo: 2.80}});
db.materiales.updateOne({nombre: "Toma Corriente Doble"}, {$set: {costo: 4.00}});
db.materiales.updateOne({nombre: "Caja Octogonal 4x4\""}, {$set: {costo: 2.00}});
db.materiales.updateOne({nombre: "Breaker 15A"}, {$set: {costo: 7.50}});
db.materiales.updateOne({nombre: "Breaker 20A"}, {$set: {costo: 8.25}});
db.materiales.updateOne({nombre: "Tubo Conduit EMT 1/2\" (3m)"}, {$set: {costo: 5.20}});
db.materiales.updateOne({nombre: "Conector EMT 1/2\""}, {$set: {costo: 1.10}});
db.materiales.updateOne({nombre: "Cinta Aislante Negra"}, {$set: {costo: 1.75}});
db.materiales.updateOne({nombre: "Martillo de Carpintero"}, {$set: {costo: 9.25}});
db.materiales.updateOne({nombre: "Destornillador Plano 6\""}, {$set: {costo: 4.25}});
db.materiales.updateOne({nombre: "Destornillador Phillips #2"}, {$set: {costo: 4.25}});
db.materiales.updateOne({nombre: "Llave Ajustable 8\""}, {$set: {costo: 13.00}});
db.materiales.updateOne({nombre: "Alicate de Presión"}, {$set: {costo: 10.50}});
db.materiales.updateOne({nombre: "Cinta Métrica 5m"}, {$set: {costo: 5.50}});
db.materiales.updateOne({nombre: "Nivel de Burbuja 60cm"}, {$set: {costo: 8.50}});
db.materiales.updateOne({nombre: "Serrucho para Madera"}, {$set: {costo: 11.50}});
db.materiales.updateOne({nombre: "Flexómetro 8m"}, {$set: {costo: 7.00}});
db.materiales.updateOne({nombre: "Guantes de Lata (par)"}, {$set: {costo: 5.50}});
db.materiales.updateOne({nombre: "Mortero Preparado (40kg)"}, {$set: {costo: 8.25}});
db.materiales.updateOne({nombre: "Yeso (25kg)"}, {$set: {costo: 10.00}});
db.materiales.updateOne({nombre: "Geomembrana (m²)"}, {$set: {costo: 5.00}});
db.materiales.updateOne({nombre: "Malla Electrosoldada 5x5"}, {$set: {costo: 19.50}});
db.materiales.updateOne({nombre: "Fibra de Vidrio (m²)"}, {$set: {costo: 4.20}});
db.materiales.updateOne({nombre: "Adhesivo Cerámico (20kg)"}, {$set: {costo: 13.50}});
db.materiales.updateOne({nombre: "Lechada para Cerámica (kg)"}, {$set: {costo: 2.75}});
db.materiales.updateOne({nombre: "Polvo de Cemento Blanco (kg)"}, {$set: {costo: 2.00}});
db.materiales.updateOne({nombre: "Cal Hidratada (25kg)"}, {$set: {costo: 8.75}});
db.materiales.updateOne({nombre: "Impermeabilizante (gal)"}, {$set: {costo: 20.00}});
db.materiales.updateOne({nombre: "Estuco Acrílico (gal)"}, {$set: {costo: 24.00}});
db.materiales.updateOne({nombre: "Sellador de Silicona (300ml)"}, {$set: {costo: 5.25}});

print("MongoDB actualizado - Total: " + db.materiales.countDocuments({}));