-- Actualizar precios en chiriqui.db
-- Primero agregar columna costo si no existe
ALTER TABLE materiales ADD COLUMN costo REAL;

UPDATE materiales SET costo = 8.75 WHERE nombre = 'Cemento Gris (42.5 kg)';
UPDATE materiales SET costo = 0.90 WHERE nombre = 'Bloque de Concreto (hueco)';
UPDATE materiales SET costo = 19.00 WHERE nombre = 'Arena Fina (m³)';
UPDATE materiales SET costo = 23.50 WHERE nombre = 'Piedra Triturada (m³)';
UPDATE materiales SET costo = 13.75 WHERE nombre = 'Varilla Corrugada 3/8"';
UPDATE materiales SET costo = 18.50 WHERE nombre = 'Varilla Corrugada 1/2"';
UPDATE materiales SET costo = 6.00 WHERE nombre = 'Alambre de Amarre #18';
UPDATE materiales SET costo = 2.90 WHERE nombre = 'Clavo de 2" (kg)';
UPDATE materiales SET costo = 2.90 WHERE nombre = 'Clavo de 3" (kg)';
UPDATE materiales SET costo = 4.90 WHERE nombre = 'Madera Pino (pulgada)';
UPDATE materiales SET costo = 3.75 WHERE nombre = 'Tubo PVC 1/2" (3m)';
UPDATE materiales SET costo = 4.50 WHERE nombre = 'Tubo PVC 3/4" (3m)';
UPDATE materiales SET costo = 0.95 WHERE nombre = 'Codo PVC 1/2"';
UPDATE materiales SET costo = 1.20 WHERE nombre = 'Tee PVC 1/2"';
UPDATE materiales SET costo = 7.00 WHERE nombre = 'Pegamento PVC (946ml)';
UPDATE materiales SET costo = 1.10 WHERE nombre = 'Cinta Teflón (rollo)';
UPDATE materiales SET costo = 0.60 WHERE nombre = 'Lija para Madera #100';
UPDATE materiales SET costo = 2.25 WHERE nombre = 'Brocha 2"';
UPDATE materiales SET costo = 4.00 WHERE nombre = 'Rodillo para Pintura 9"';
UPDATE materiales SET costo = 2.50 WHERE nombre = 'Bandeja para Pintura';
UPDATE materiales SET costo = 26.00 WHERE nombre = 'Pintura Latex Blanca (gal)';
UPDATE materiales SET costo = 32.50 WHERE nombre = 'Pintura Esmalte Azul (gal)';
UPDATE materiales SET costo = 32.50 WHERE nombre = 'Pintura Esmalte Rojo (gal)';
UPDATE materiales SET costo = 14.00 WHERE nombre = 'Thinner (gal)';
UPDATE materiales SET costo = 17.00 WHERE nombre = 'Sellador (gal)';
UPDATE materiales SET costo = 5.00 WHERE nombre = 'Masilla (kg)';
UPDATE materiales SET costo = 3.00 WHERE nombre = 'Espátula 4"';
UPDATE materiales SET costo = 1.35 WHERE nombre = 'Cinta de Enmascarar (24mm)';
UPDATE materiales SET costo = 40.00 WHERE nombre = 'Cable THHN #12 (100m)';
UPDATE materiales SET costo = 61.50 WHERE nombre = 'Cable THHN #10 (100m)';
UPDATE materiales SET costo = 2.80 WHERE nombre = 'Interruptor Sencillo';
UPDATE materiales SET costo = 4.00 WHERE nombre = 'Toma Corriente Doble';
UPDATE materiales SET costo = 2.00 WHERE nombre = 'Caja Octogonal 4x4"';
UPDATE materiales SET costo = 7.50 WHERE nombre = 'Breaker 15A';
UPDATE materiales SET costo = 8.25 WHERE nombre = 'Breaker 20A';
UPDATE materiales SET costo = 5.20 WHERE nombre = 'Tubo Conduit EMT 1/2" (3m)';
UPDATE materiales SET costo = 1.10 WHERE nombre = 'Conector EMT 1/2"';
UPDATE materiales SET costo = 1.75 WHERE nombre = 'Cinta Aislante Negra';
UPDATE materiales SET costo = 9.25 WHERE nombre = 'Martillo de Carpintero';
UPDATE materiales SET costo = 4.25 WHERE nombre = 'Destornillador Plano 6"';
UPDATE materiales SET costo = 4.25 WHERE nombre = 'Destornillador Phillips #2';
UPDATE materiales SET costo = 13.00 WHERE nombre = 'Llave Ajustable 8"';
UPDATE materiales SET costo = 10.50 WHERE nombre = 'Alicate de Presión';
UPDATE materiales SET costo = 5.50 WHERE nombre = 'Cinta Métrica 5m';
UPDATE materiales SET costo = 8.50 WHERE nombre = 'Nivel de Burbuja 60cm';
UPDATE materiales SET costo = 11.50 WHERE nombre = 'Serrucho para Madera';
UPDATE materiales SET costo = 7.00 WHERE nombre = 'Flexómetro 8m';
UPDATE materiales SET costo = 5.50 WHERE nombre = 'Guantes de Lata (par)';
UPDATE materiales SET costo = 8.25 WHERE nombre = 'Mortero Preparado (40kg)';
UPDATE materiales SET costo = 10.00 WHERE nombre = 'Yeso (25kg)';
UPDATE materiales SET costo = 5.00 WHERE nombre = 'Geomembrana (m²)';
UPDATE materiales SET costo = 19.50 WHERE nombre = 'Malla Electrosoldada 5x5';
UPDATE materiales SET costo = 4.20 WHERE nombre = 'Fibra de Vidrio (m²)';
UPDATE materiales SET costo = 13.50 WHERE nombre = 'Adhesivo Cerámico (20kg)';
UPDATE materiales SET costo = 2.75 WHERE nombre = 'Lechada para Cerámica (kg)';
UPDATE materiales SET costo = 2.00 WHERE nombre = 'Polvo de Cemento Blanco (kg)';
UPDATE materiales SET costo = 8.75 WHERE nombre = 'Cal Hidratada (25kg)';
UPDATE materiales SET costo = 20.00 WHERE nombre = 'Impermeabilizante (gal)';
UPDATE materiales SET costo = 24.00 WHERE nombre = 'Estuco Acrílico (gal)';
UPDATE materiales SET costo = 5.25 WHERE nombre = 'Sellador de Silicona (300ml)';