use materiales_ibarra;

var materiales = [
    {nombre: "Cemento Gris (42.5 kg)", costo: 8.75, cantidad: 500, descripcion: "Cemento Portland tipo I, saco de 42.5 kg", activo: true, categoria: "Cemento"},
    {nombre: "Bloque de Concreto (hueco)", costo: 0.90, cantidad: 2000, descripcion: "Bloque estándar 20x20x40 cm", activo: true, categoria: "Bloques"},
    {nombre: "Arena Fina (m³)", costo: 19.00, cantidad: 150, descripcion: "Arena lavada para construcción", activo: true, categoria: "Agregados"},
    {nombre: "Piedra Triturada (m³)", costo: 23.50, cantidad: 120, descripcion: "Piedra 3/4 para concreto", activo: true, categoria: "Agregados"},
    {nombre: "Varilla Corrugada 3/8\"", costo: 13.75, cantidad: 300, descripcion: "Acero de refuerzo, longitud 6m", activo: true, categoria: "Acero"},
    {nombre: "Varilla Corrugada 1/2\"", costo: 18.50, cantidad: 200, descripcion: "Acero de refuerzo, longitud 6m", activo: true, categoria: "Acero"},
    {nombre: "Alambre de Amarre #18", costo: 6.00, cantidad: 150, descripcion: "Rollo de 5 kg", activo: true, categoria: "Acero"},
    {nombre: "Clavo de 2\" (kg)", costo: 2.90, cantidad: 80, descripcion: "Clavo acero galvanizado", activo: true, categoria: "Ferretería"},
    {nombre: "Clavo de 3\" (kg)", costo: 2.90, cantidad: 75, descripcion: "Clavo acero galvanizado", activo: true, categoria: "Ferretería"},
    {nombre: "Madera Pino (pulgada)", costo: 4.90, cantidad: 400, descripcion: "Tabla de 1\" x 4\" x 12'", activo: true, categoria: "Madera"},
    {nombre: "Tubo PVC 1/2\" (3m)", costo: 3.75, cantidad: 250, descripcion: "Tubería hidráulica blanca", activo: true, categoria: "Plomería"},
    {nombre: "Tubo PVC 3/4\" (3m)", costo: 4.50, cantidad: 200, descripcion: "Tubería hidráulica blanca", activo: true, categoria: "Plomería"},
    {nombre: "Codo PVC 1/2\"", costo: 0.95, cantidad: 500, descripcion: "Codo 90° para agua", activo: true, categoria: "Plomería"},
    {nombre: "Tee PVC 1/2\"", costo: 1.20, cantidad: 300, descripcion: "Conexión en T", activo: true, categoria: "Plomería"},
    {nombre: "Pegamento PVC (946ml)", costo: 7.00, cantidad: 60, descripcion: "Cemento para tuberías", activo: true, categoria: "Plomería"},
    {nombre: "Cinta Teflón (rollo)", costo: 1.10, cantidad: 200, descripcion: "Sellador para roscas", activo: true, categoria: "Plomería"},
    {nombre: "Lija para Madera #100", costo: 0.60, cantidad: 150, descripcion: "Hoja de lija", activo: true, categoria: "Herramientas"},
    {nombre: "Brocha 2\"", costo: 2.25, cantidad: 100, descripcion: "Brocha para pintura", activo: true, categoria: "Pintura"},
    {nombre: "Rodillo para Pintura 9\"", costo: 4.00, cantidad: 80, descripcion: "Con mango y esponja", activo: true, categoria: "Pintura"},
    {nombre: "Bandeja para Pintura", costo: 2.50, cantidad: 70, descripcion: "Bandeja plástica", activo: true, categoria: "Pintura"},
    {nombre: "Pintura Latex Blanca (gal)", costo: 26.00, cantidad: 120, descripcion: "Pintura para interiores", activo: true, categoria: "Pintura"},
    {nombre: "Pintura Esmalte Azul (gal)", costo: 32.50, cantidad: 60, descripcion: "Esmalte sintético", activo: true, categoria: "Pintura"},
    {nombre: "Pintura Esmalte Rojo (gal)", costo: 32.50, cantidad: 55, descripcion: "Esmalte sintético", activo: true, categoria: "Pintura"},
    {nombre: "Thinner (gal)", costo: 14.00, cantidad: 40, descripcion: "Diluyente para pintura", activo: true, categoria: "Pintura"},
    {nombre: "Sellador (gal)", costo: 17.00, cantidad: 45, descripcion: "Primer para paredes", activo: true, categoria: "Pintura"},
    {nombre: "Masilla (kg)", costo: 5.00, cantidad: 100, descripcion: "Para reparar paredes", activo: true, categoria: "Pintura"},
    {nombre: "Espátula 4\"", costo: 3.00, cantidad: 90, descripcion: "Para aplicar masilla", activo: true, categoria: "Herramientas"},
    {nombre: "Cinta de Enmascarar (24mm)", costo: 1.35, cantidad: 200, descripcion: "Cinta para protección", activo: true, categoria: "Pintura"},
    {nombre: "Cable THHN #12 (100m)", costo: 40.00, cantidad: 50, descripcion: "Cable eléctrico calibre 12", activo: true, categoria: "Eléctrico"},
    {nombre: "Cable THHN #10 (100m)", costo: 61.50, cantidad: 35, descripcion: "Cable eléctrico calibre 10", activo: true, categoria: "Eléctrico"},
    {nombre: "Interruptor Sencillo", costo: 2.80, cantidad: 150, descripcion: "Interruptor 15A, blanco", activo: true, categoria: "Eléctrico"},
    {nombre: "Toma Corriente Doble", costo: 4.00, cantidad: 140, descripcion: "Tomacorriente 15A", activo: true, categoria: "Eléctrico"},
    {nombre: "Caja Octogonal 4x4\"", costo: 2.00, cantidad: 200, descripcion: "Caja metálica para conexiones", activo: true, categoria: "Eléctrico"},
    {nombre: "Breaker 15A", costo: 7.50, cantidad: 80, descripcion: "Interruptor termomagnético", activo: true, categoria: "Eléctrico"},
    {nombre: "Breaker 20A", costo: 8.25, cantidad: 70, descripcion: "Interruptor termomagnético", activo: true, categoria: "Eléctrico"},
    {nombre: "Tubo Conduit EMT 1/2\" (3m)", costo: 5.20, cantidad: 100, descripcion: "Tubería metálica", activo: true, categoria: "Eléctrico"},
    {nombre: "Conector EMT 1/2\"", costo: 1.10, cantidad: 300, descripcion: "Conector para tubería", activo: true, categoria: "Eléctrico"},
    {nombre: "Cinta Aislante Negra", costo: 1.75, cantidad: 180, descripcion: "Cinta vinílica 3M", activo: true, categoria: "Eléctrico"},
    {nombre: "Martillo de Carpintero", costo: 9.25, cantidad: 50, descripcion: "Con mango de madera", activo: true, categoria: "Herramientas"},
    {nombre: "Destornillador Plano 6\"", costo: 4.25, cantidad: 60, descripcion: "Punta magnética", activo: true, categoria: "Herramientas"},
    {nombre: "Destornillador Phillips #2", costo: 4.25, cantidad: 60, descripcion: "Punta magnética", activo: true, categoria: "Herramientas"},
    {nombre: "Llave Ajustable 8\"", costo: 13.00, cantidad: 40, descripcion: "Llave perica", activo: true, categoria: "Herramientas"},
    {nombre: "Alicate de Presión", costo: 10.50, cantidad: 45, descripcion: "Alicate universal", activo: true, categoria: "Herramientas"},
    {nombre: "Cinta Métrica 5m", costo: 5.50, cantidad: 70, descripcion: "Cinta de acero", activo: true, categoria: "Herramientas"},
    {nombre: "Nivel de Burbuja 60cm", costo: 8.50, cantidad: 35, descripcion: "Aluminio, 3 burbujas", activo: true, categoria: "Herramientas"},
    {nombre: "Serrucho para Madera", costo: 11.50, cantidad: 30, descripcion: "Hoja de 20\"", activo: true, categoria: "Herramientas"},
    {nombre: "Flexómetro 8m", costo: 7.00, cantidad: 55, descripcion: "Con freno y gancho", activo: true, categoria: "Herramientas"},
    {nombre: "Guantes de Lata (par)", costo: 5.50, cantidad: 80, descripcion: "Guantes de carnaza", activo: true, categoria: "Protección"},
    {nombre: "Mortero Preparado (40kg)", costo: 8.25, cantidad: 120, descripcion: "Mezcla lista para pegar bloques", activo: true, categoria: "Morteros"},
    {nombre: "Yeso (25kg)", costo: 10.00, cantidad: 90, descripcion: "Para acabados de pared", activo: true, categoria: "Acabados"},
    {nombre: "Geomembrana (m²)", costo: 5.00, cantidad: 500, descripcion: "Para impermeabilización", activo: true, categoria: "Impermeabilización"},
    {nombre: "Malla Electrosoldada 5x5", costo: 19.50, cantidad: 60, descripcion: "Rollo 2x20m", activo: true, categoria: "Acero"},
    {nombre: "Fibra de Vidrio (m²)", costo: 4.20, cantidad: 200, descripcion: "Para refuerzos", activo: true, categoria: "Refuerzos"},
    {nombre: "Adhesivo Cerámico (20kg)", costo: 13.50, cantidad: 80, descripcion: "Pegamento para baldosas", activo: true, categoria: "Cerámica"},
    {nombre: "Lechada para Cerámica (kg)", costo: 2.75, cantidad: 150, descripcion: "Para juntas", activo: true, categoria: "Cerámica"},
    {nombre: "Polvo de Cemento Blanco (kg)", costo: 2.00, cantidad: 200, descripcion: "Para acabados finos", activo: true, categoria: "Acabados"},
    {nombre: "Cal Hidratada (25kg)", costo: 8.75, cantidad: 70, descripcion: "Para mezclas", activo: true, categoria: "Materiales"},
    {nombre: "Impermeabilizante (gal)", costo: 20.00, cantidad: 45, descripcion: "Líquido para muros", activo: true, categoria: "Impermeabilización"},
    {nombre: "Estuco Acrílico (gal)", costo: 24.00, cantidad: 55, descripcion: "Acabado texturizado", activo: true, categoria: "Acabados"},
    {nombre: "Sellador de Silicona (300ml)", costo: 5.25, cantidad: 120, descripcion: "Transparente, para baños", activo: true, categoria: "Selladores"},
];

db.materiales.insertMany(materiales);
print("✅ 60 materiales insertados con precios actualizados");
print("Total: " + db.materiales.countDocuments({}));